---
title: "LNI public injury data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(pacman)
p_load(datasets, ggplot2, data.table, shiny)
rate = readRDS("C:/Users/elaustin/OneDrive/Documents/UW Postdoc/PNASH/DataCOD/Logging/rate_table.RDS")
```

```{r setup, include=FALSE}
library(flexdashboard)
```

Inputs {.sidebar}
-----------------------------------------------------------------------


```{r}

selectizeInput('sicval', 'Industry Group', unique(rate$`SIC Description`),
               selected = "DAIRY FARMS")

selectInput('ycol', 'Industry Group', c("Total Number of Firms", 
                                           "Number of Claim-Free Firms",
                                           "Claims per 200000 hr"),
                selected="Claims per 200000 hr")
    
sliderInput("range", "Range:",
                  min = min(rate$year), max = max(rate$year),
                  step = 1, value = c(min(rate$year), max(rate$year)))

selectInput('group', 'Firm Size', choices = levels(rate$`Firm Size`), 
            selected = "50+ Employees")


```


Column {.tabset}
-----------------------------------------------------------------------

###Rate plot


```{r}
palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
  "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

# Combine the selected variables into a new data frame
selectedData <- reactive({
  newdata = copy(rate)
  newdata = rate[year %in% input$range[1]:input$range[2] &
         `SIC Description` %in% input$sicval &
         `Firm Size` %in% input$group, ]
  setnames(newdata,input$ycol, "y" )
  newdata
})

plotTitle <- reactive({
  paste("Claims per 100 Full Time Workers for", input$sicval )
})

renderPlot({
  
  waprivate = data.table(Year = c(2006:2015), 
                         Injury = c(6.6, 6.1, 5.6, 5.1, 4.8, 4.9, 4.8, 4.75, 4.6, 4.5))
  
  ggplot(data = data.table(selectedData()), aes(as.numeric(year), as.numeric(y)),
         color= input$group) + 
  geom_point() + stat_smooth(se=F, span = 0.8) + 
  theme_light(14)+ xlab("") + ggtitle(plotTitle()) +
  ylab(input$ycol) +
  scale_x_continuous(breaks = input$range[1]:input$range[2], 
                     minor_breaks = input$range[1]:input$range[2]) +
  geom_point(data  = waprivate, aes(Year, Injury, color="WA All Private Sector")) + 
  stat_smooth(data  = waprivate, aes(Year, Injury, color="WA All Private Sector"), se=F) + theme(legend.position="bottom") +
  labs(color = "Firm Size")

})
```


###Experience Factor Distribution

```{r}
palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
  "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

# Combine the selected variables into a new data frame
efdata <- reactive({
  newdata = copy(rate)
  newdata = rate[year %in% input$range[1]:input$range[2] &
         `SIC Description` %in% input$sicval &
         `Firm Size` %in% input$group, ]
    setnames(newdata,input$ycol, "y" )
    newdata[, grep(experience,colnames(newdata), ignore.case= T, value = T)]
    melt(newdata[,-c("SIC Code", "SIC Description","Firm Size", 
                     "Number of Claim-Free Firms")])
  newdata
})

plotTitle <- reactive({
  paste("Claims per 100 Full Time Workers for", input$sicval )
})

renderPlot({
  
  
  
  waprivate = data.table(Year = c(2006:2015), 
                         Injury = c(6.6, 6.1, 5.6, 5.1, 4.8, 4.9, 4.8, 4.75, 4.6, 4.5))
  
  ggplot(data = data.table(selectedData()), aes(as.numeric(year), as.numeric(y)),
         color= input$group) + 
  geom_point() + stat_smooth(se=F, span = 0.8) + 
  theme_light(14)+ xlab("") + ggtitle(plotTitle()) +
  ylab(input$ycol) +
  scale_x_continuous(breaks = input$range[1]:input$range[2], 
                     minor_breaks = input$range[1]:input$range[2]) +
  geom_point(data  = waprivate, aes(Year, Injury, color="WA All Private Sector")) + 
  stat_smooth(data  = waprivate, aes(Year, Injury, color="WA All Private Sector"), se=F) + theme(legend.position="bottom") +
  labs(color = "Firm Size")

})
```