---
title: "US BLS Agricultural Worker Fatalities: PNW States"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    theme: readable
    vertical_layout: scroll 
editor_options: 
  chunk_output_type: console
runtime: shiny
---


```{r setup, include=FALSE}
# Attach packages, installing as needed
#about / fatalities/demographics/description of injury/table download
if(!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(here, readr, dplyr, tidyr, stringr, purrr, forcats, DT, 
               data.table, flexdashboard, ggplot2, plotly, shiny)

pacman::p_load_gh("dreamRs/shinytreeview")

# Set options
options(readr.show_col_types = FALSE, readr.show_progress = FALSE)

# Read data file
data_dir <- here("Fatality Data NW")
rds_file <- here(data_dir, 'long-bls-fatal-aff-11-21.rds')
csv_file <- here(data_dir, 'long-bls-fatal-aff-11-21.csv')
if (file.exists(rds_file)) {
  df <- readRDS(rds_file)
  df = df[df$Fatalities>0 & !is.na(df$Fatalities),]
} else {
  df <- read_csv(csv_file)
  df = df[df$Fatalities>0 & !is.na(df$Fatalities),]
  saveRDS(df, rds_file)
}

# # Find level-1 Characteristics
# Char_1 <- df %>% pull(!is.na(Char_2), is.na(Char_3)) %>% pull(Char_1) %>% 
#   unique()

# Read NAICS codes and set levels based on presence of digits
naics <- read_csv(here(data_dir, "ind_codes.csv") )
naics <- naics %>% mutate(level = str_count(code, '\\d')) %>%
  mutate(level = ifelse(code %in% c("GP2AFH"), 2, level))

naics = naics %>%  
  mutate(code3 = substr (code, 1, 3), code2 = substr (code, 1, 2))

naics = naics  %>% 
  mutate(code2 = ifelse(code2 == "GP", 11, code2))

# Create nested structure using level
naics <- naics %>% 
  mutate(level_1 = ifelse(level == 1, name, NA),
         level_2 = ifelse(level == 2, name, NA),
         level_3 = ifelse(level == 3, name, NA),
         level_4 = ifelse(level == 4, name, NA),
         level_5 = ifelse(level == 5, name, NA),
         level_6 = ifelse(level == 6, name, NA)) %>% 
  fill(starts_with("level_")) %>% select(c(-level_1)) %>%
  mutate(level_2 = ifelse(code == "3117XX", "Manufacturing", level_2),
         level_3 = ifelse(code == "3117XX", "Food Manufacturing", level_3),
         level_4 = ifelse(code == "3117XX", name, level_4),
         level_5 = ifelse(code == "3117XX", NA, level_5),
         level_6 = ifelse(code == "3117XX", NA, level_6))

naics <- naics %>% 
  group_by(code2) %>%  
  fill( level_2)

charvals = df %>% 
  select(Char_1, Char_2, Char_3, Char_4, Char_5) %>% unique() %>% 
  mutate(Char_1_id = Char_1) %>%
  mutate(Char_2_id = 
           ifelse(!is.na(Char_2), paste(Char_1_id, Char_2, sep = ";"), NA)) %>%
  mutate(Char_3_id = 
           ifelse(!is.na(Char_3), paste(Char_2_id, Char_3, sep = ";"), NA)) %>%
  mutate(Char_4_id = 
           ifelse(!is.na(Char_4), paste(Char_3_id, Char_4, sep = ";"), NA)) %>%
  mutate(Char_5_id = 
           ifelse(!is.na(Char_5), paste(Char_4_id, Char_5, sep = ";"), NA)) 
  
df = df %>% merge(charvals, 
                  by = c('Char_1', 'Char_2', 'Char_3', 'Char_4', 'Char_5'))

df = merge(df, naics, by= "code")


```


```{r, include = FALSE}


#make intergers for plot axes
integer_breaks <- function(n = 5, ...) {
  fxn <- function(x) {
    breaks <- floor(pretty(x, n, ...))
    names(breaks) <- attr(breaks, "labels")
    breaks
  }
  return(fxn)
}
# Define a function to make a generic ggplot object without any geoms
make_ggplot <- function(df, x_label, by = 'State', wrap_width = 50, 
                        color = FALSE) {
  p_levels <- df %>% pull(Characteristic) %>% unique()
  p_labels <- p_levels %>% str_wrap(width = wrap_width)
  df <- df %>% 
    mutate(Characteristic = factor(Characteristic, 
                                   levels = p_levels,
                                   labels = p_labels)) %>%
    select(State, !!x_label := Characteristic, Year, Fatalities) %>% 
    drop_na(Fatalities)
  if (color == FALSE) {
    ggplot(df, aes(x = .data[[x_label]], y = Fatalities))
  } else {
    x_var <- ifelse(by == 'State', 'Year', 'State')
    ggplot(df, aes(x = .data[[x_var]], y = Fatalities, 
                   color = .data[[x_label]], fill = .data[[x_label]]))
  }
}

# Define a function to make a generic ggplot object without any geoms 
# filtered by Char_1 == Char1
make_ggplot_1 <- function (df, Char1, Char2 = NULL, Char3 = NULL, by = 'State', 
                           wrap_width = 50, color = FALSE) {
  df <- df %>% 
    filter(Char_1 == Char1, !is.na(Char_2), is.na(Char_3)) %>% 
    select("Characteristic" = Char_2, Fatalities, State, Year)
  make_ggplot(df, Char1, by = by, wrap_width = wrap_width, color = color)
}

# Define a function to make a generic ggplot object without any geoms 
# filtered by Char_1 == Char1 and Char_2 == Char2
make_ggplot_2 <- function (df, Char1, Char2, Char3 = NULL, by = 'State', 
                           wrap_width = 50, color = FALSE) {
  df <- df %>% 
    filter(Char_1 == Char1, Char_2 == Char2, !is.na(Char_3), is.na(Char_4)) %>% 
    select("Characteristic" = Char_3, Fatalities, State, Year)
  make_ggplot(df, Char2, by = by, wrap_width = wrap_width, color = color)
}

# Define a function to make a generic ggplot object without any geoms 
# filtered by Char_1 == Char1 and Char_2 == Char2 and Char_3 == Char3
make_ggplot_3 <- function (df, Char1, Char2, Char3, by = 'State', 
                           wrap_width = 50, color = FALSE) {
  df <- df %>% 
    filter(Char_1 == Char1, Char_2 == Char2, Char_3 == Char3, 
           !is.na(Char_4), is.na(Char_5)) %>% 
    select("Characteristic" = Char_4, Fatalities, State, Year)
  make_ggplot(df, Char3, by = by, wrap_width = wrap_width, color = color)
}

# Define a function to make a box plot building upon a generic ggplot object
make_boxplot <- function(df, Char_1, Char_2 = NULL, Char_3 = NULL, by = 'State', 
                         wrap_width = 50, nrow = NULL, color = FALSE, 
                         FUN = NULL) {
  if (is.null(nrow)) nrow <- ifelse(by == "Year", 2, 1)
  if (is.null(FUN)) {
    FUN = case_when(
      is.null(Char_2) && is.null(Char_3) ~ "make_ggplot_1",
      !is.null(Char_2) && is.null(Char_3) ~ "make_ggplot_2",
      .default = "make_ggplot_3"
    )
  }
  
  arg <- list(df = df, Char1 = Char_1, Char2 = Char_2, Char3 = Char_3, by = by,
              wrap_width = wrap_width)
  do.call(FUN, arg) + geom_boxplot() + facet_wrap(by, nrow = nrow) + 
    coord_flip()
}

# Define a function to make a scatter plot building upon a generic ggplot object
make_scatterplot <- function(df, Char_1, Char_2 = NULL, Char_3 = NULL, 
                             by = 'State', wrap_width = 50, color = TRUE, 
                             nrow = NULL, FUN = NULL) {
  if (is.null(nrow)) nrow <- ifelse(by == "Year", 2, 1)
  if (is.null(FUN)) {
    FUN = case_when(
      is.null(Char_2) && is.null(Char_3) ~ "make_ggplot_1",
      !is.null(Char_2) && is.null(Char_3) ~ "make_ggplot_2",
      .default = "make_ggplot_3"
    )
  }
  
  arg <- list(df = df, Char1 = Char_1, Char2 = Char_2, Char3 = Char_3, by = by,
              wrap_width = wrap_width, color = color)
  flip <- if (by == "Year") coord_flip()
  smooth <- if (by == "State") geom_smooth(method = "lm", formula = y ~ x)
  do.call(FUN, arg) + geom_point() + 
    smooth + facet_wrap(by, nrow = nrow) + flip
}

# Define a function to make a bar plot building upon a generic ggplot object
make_barplot <- function(df, Char_1, Char_2 = NULL, Char_3 = NULL, 
                             by = 'State', wrap_width = 50, color = TRUE, 
                             nrow = NULL, FUN = NULL) {
  if (is.null(nrow)) nrow <- ifelse(by == "Year", 2, 1)
  if (is.null(FUN)) {
    FUN = case_when(
      is.null(Char_2) && is.null(Char_3) ~ "make_ggplot_1",
      !is.null(Char_2) && is.null(Char_3) ~ "make_ggplot_2",
      .default = "make_ggplot_3"
    )
  }
  
  arg <- list(df = df, Char1 = Char_1, Char2 = Char_2, Char3 = Char_3, by = by,
              wrap_width = wrap_width, color = color)
  flip <- if (by == "Year") coord_flip()
  fill_color <- ifelse(by == "Year", "State", "Year")
  do.call(FUN, arg) + geom_col() + facet_wrap(by, nrow = nrow) + flip
}

plot_bar_char <- function(df, Char, nrow = 1, wrap_width = 60) {
  ggplot(df %>% 
           filter(Characteristic %in% Char) %>% 
           mutate(Year = factor(Year)) %>%
           mutate(Characteristic = str_wrap(Characteristic, wrap_width)) %>%
           group_by(Characteristic, State, Year) %>%
           summarise(Fatalities = sum(Fatalities, na.rm = TRUE), 
                     .groups = "drop"), 
  aes(x = Year, Fatalities, fill = State)) + geom_col() + 
    facet_wrap("Characteristic", nrow = nrow)
}
```

```{r, include=FALSE}
# Top-5 Characteristics to plot at finer detail
df %>% filter(!is.na(Char_1), !is.na(Char_2), !is.na(Char_3)) %>% 
  group_by(Char_1, Char_2) %>% 
  summarise(Fatalities = sum(Fatalities, na.rm = TRUE)) %>% 
  filter(Fatalities != 0) %>% arrange(desc(Fatalities), Char_1, Char_2) %>% 
  head(5)

# Top-15 Characteristics to plot at even finer detail
df %>% filter(!is.na(Char_1), !is.na(Char_2), !is.na(Char_3), !is.na(Char_4)) %>%
group_by(Char_1, Char_2, Char_3) %>%
summarise(Fatalities = sum(Fatalities, na.rm = TRUE)) %>%
filter(Fatalities != 0) %>% arrange(desc(Fatalities), Char_1, Char_2, Char_3) %>%
head(15)

# Top-3 Level-3 Characteristics per Category
cats <- unique(df$Char_1)
top3 <- map(cats, ~ df %>% filter(Char_1 == .x, !is.na(Char_2), 
                                  !is.na(Char_3), is.na(Char_4)) %>%
              group_by(Characteristic) %>% 
              summarise(Fatalities = sum(Fatalities, na.rm = TRUE), 
                        .groups = "drop") %>% 
              arrange(desc(Fatalities)) %>% head(3) %>% 
              pull(Characteristic)) %>% setNames(cats)
```

About
=====================================

This page shows fatalities in the PNW.

Fatalities
===================================== 

Inputs {.sidebar data-width=400}
-----------------------------------------------------------------------


```{r}

treecheckInput(
    inputId = "naicsval",
    label = "Choose an Industry Group:",
    choices = make_tree(
      data = naics, 
      levels = c("level_2", "level_3", "level_4", "level_5","level_6") ))
    
sliderInput("year", "Year:",
            min = min(df$Year, na.rm=T), sep = "",
            max = max(df$Year, na.rm=T), value = c(min(df$Year, na.rm=T), 
                                                   max(df$Year, na.rm=T)))

selectInput('state', 'State', choices = unique(df$State), 
            selected = c("Washington"),  multiple = FALSE)

treecheckInput(
    inputId = "char",
    label = "Choose specific injury characteristics:",
    choices = make_tree(
      data = charvals, 
      levels = c("Char_1", "Char_2", "Char_3"),
      levels_id = c("Char_1_id", "Char_2_id", "Char_3_id"),
      return_value = "id"))

```

Column {.tabset}
-----------------------------------------------------------------------

### Total Fatalities over time


```{r}

total_fatalities <- reactive ({
  mydata = copy(df)
  
  mycode = naics %>% 
    filter(name %in% input$naicsval) %>%
    select(code)
  mycode = mycode$code
    
  df_total <- mydata %>%
  filter(State %in% input$state, code %in% mycode, is.na(Char_4),
         Char_1_id %in% input$char |
           Char_2_id %in% input$char |
           Char_3_id %in% input$char) %>%
    
  group_by(Year, State, level, name, Char_1, Char_2, Char_3) %>% 
  summarize(Fatalities = sum(Fatalities, na.rm = TRUE), .groups= "drop") %>%
  filter(Fatalities != 0) %>% arrange(State, Year, level, name, Fatalities)
  
  df_total = df_total %>% 
    mutate(Characteristic = ifelse(is.na(Char_3), 
                                   ifelse(is.na(Char_2), Char_1, Char_2), 
                                   Char_3))
  
  minval= min(df_total$level)
  df_total = df_total[df_total$level == minval,]
  df_total= df_total %>% select_if(~sum(!is.na(.)) > 0)
  df_total = df_total  %>% drop_na() 
  df_total
  })


renderPlotly({
  
  plotdata = NULL
  try({
  plotdata = (total_fatalities())}, silent = T)
  
  print(input$char)
  print(input$naicsval)
  print(plotdata)
  
  if(nrow(plotdata) > 0 & length(input$naicsval) > 0 & length(input$char) > 0){
 p <- ggplot(plotdata, aes(x = Year, y = Fatalities, 
                           color = Characteristic)) + 
   geom_point() + 
    facet_wrap("State", nrow = 1) + 
   geom_smooth(se = F) + 
   labs(color="Sub-Groups") +
   scale_x_continuous(breaks = integer_breaks()) + 
    scale_y_continuous(breaks = integer_breaks(), 
                       limits = c(0, max(plotdata$Fatalities,na.rm=T)+5)) +
   ggtitle(unique(plotdata$name))
   
    
  ggplotly(p)
  } else if (length(input$naicsval) == 0)
    ggplot()+ggtitle("Please use the menu to select an industy group. Use the > symbol to navigate through levels.")
  else ggplot()+ggtitle("No data exists for the combination of variables you selected. Please modify your selection.")
  

})

```
